IF EXISTS(SELECT * FROM sys.server_event_sessions WHERE name='Backup trace')
    DROP EVENT session [Backup trace] ON SERVER;
GO
CREATE EVENT SESSION [Backup trace] ON SERVER 
ADD EVENT sqlserver.backup_restore_progress_trace 
ADD TARGET package0.event_file(SET filename=N'Backup trace')
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO

-- Start the event session
ALTER EVENT SESSION [Backup trace]
ON SERVER
STATE = start;
GO

BACKUP DATABASE ADVENTUREWORKS2016 TO DISK='C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\Backup\adw2012.bak' WITH INIT, STATS=5

RESTORE DATABASE ADVENTUREWORKS2016 FROM DISK='C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\Backup\adw2012.bak' WITH STATS=5

